// Lagos State Location Data
export const lagosLocationData = {
  AGEGE: [
    "Atobaje",
    "Darocha",
    "Iloro/Onipetesi",
    "Isale Odo/Ayige",
    "Isale/Idi Mangoro",
    "Keke",
    "Okekoto",
    "Oniwaya/Papa-Uku",
    "Orile Agege/Oko Oba",
    "Oyewole/Papa Ashofa",
    "Sango",
    "Tabon Tabon/Oko Oba",
  ],
  "AJEROMI/IFELODUN": [
    "Aiyetoro",
    "Alaba",
    "Alakoto/Ibafon",
    "Amukoko",
    "Apasa Amukoko",
    "Awodi-Ora",
    "Bale Alaiyebiagba",
    "Ibafon",
    "Layeni-Okoya",
    "Mosafeje",
    "Ojo Road",
    "Ojora Amukoko",
    "Oke Ora",
    "Oluwa/Akere",
    "Owoyemi",
    "Temidire",
    "Tolu",
    "Wilmer",
  ],
  ALIMISHO: [
    "Abesan",
    "Abaranje/Okerube",
    "Aboru",
    "Abule-Egba",
    "Abule-Oki",
    "Agbelekale",
    "Ajasa/Amikanle",
    "Akesan-Obadore",
    "Akowonjo-Ilupeju",
    "Alagbado Alakuko",
    "Alagutan",
    "Atan Lagos",
    "Ayobo",
    "Bada-Megida",
    "Baruwa",
    "Egan",
    "Egbe-Agodo",
    "Egbe-Liasu Road",
    "Gowon Estate",
    "Idimu",
    "Igando",
    "Ijegun",
    "Ipaja",
    "Isheri Oshun",
    "Isheri Olofin",
    "Mosan/Akinogun",
    "Oguntade/Bameke",
    "Oke-Odo",
    "Okunola",
    "Omituntun-Olori",
    "Santos-Ilupeju",
    "Unity Estate",
  ],
  "AMUWO ODOFIN": [
    "Abule Osun Onireke",
    "Ado Soba",
    "Agboju",
    "Eko Akete",
    "Fastac",
    "Irede",
    "Ibeshe",
    "Ifelodun",
    "Ilado Tomaro",
    "Kirikiri",
    "Odofin",
    "Orire",
  ],
  APAPA: [
    "Abete",
    "Alafia",
    "Anjorin",
    "Apapa",
    "Badia",
    "Gaskiya",
    "Ijora",
    "Marina Beach",
    "Oduduwa",
    "Owoseni",
    "Sari Iganmu",
  ],
  EPE: [
    "Agbowa",
    "Agbowa 2/Ado",
    "Aiyetoro/Lagbade/Agbala/Oloto",
    "Alaganade",
    "Ajebo Orugbo",
    "Bado/Ebole/Etita/Iberikodo",
    "Ejinrin",
    "Ejinrin/Ketu",
    "Epe",
    "Eredo",
    "Ibonwon",
    "Ifesowapo/Temu Oke-Oso",
    "Mayunre-Oriba",
    "Mayunre-Oriba/Orepete",
    "Naforoja/Poka",
    "Odomola",
    "Odoragunsin",
    "Olugbokere/Abomiti",
    "Owu/Ota",
    "Sagida/Okeposu",
  ],
  "ETI-OSA": [
    "1004 Aboyade",
    "Addo/Okeira",
    "Ajah",
    "Ajiran/Osapa",
    "Apese/6 Extension",
    "Badore/Langbasa",
    "Falomo/Onikan",
    "Igbo-Efon/Maiyegun",
    "Ijeh/Dolfin Estate",
    "Ikate/Lekki",
    "Ilasan/Olori",
    "Kuramo/Okun Alfa",
    "Maroko/Okun Alfa/Sandfill",
    "Obalende",
    "Okun Ajah/Okun Mopo",
    "Sangotedo",
    "Tarkwa Bay",
  ],
  "IBEJU-LEKKI": [
    "Abraham Adesanya",
    "Ibeju",
    "Ise/Igbogun",
    "Iwerekun",
    "Orimedu",
    "GRA",
    "Awoyaya",
    "Lakowe",
    "Bogije",
    "Egbeda",
  ],
  "IFAKO IJAIYE": [
    "Abule-Egba",
    "Agbado Dalemo",
    "Alagbado/Kollinton",
    "Alakuko Ajegunle",
    "Ifako Pele",
    "Ifako Gbirinmi",
    "Ifako Coker",
    "Ijaiye Oke-Ira",
    "Ijaiye Ifako",
    "Iju Ishaga",
    "Iju Obawole",
    "Iju Ogundimu",
    "Isoyin",
    "Ipakodo",
    "Irepodun",
    "Isawo",
    "Isale",
    "Isiu",
    "Itumokun",
    "Itunpate/Itumaja",
    "Maja",
    "Majidun",
    "Odogunyan",
    "Oke-Eletu/Abule-Eko",
    "Olori/Eyita",
    "Oke-Oyinbo/Aiyetoro",
    "Olorunda",
    "Owutu",
    "Sholafun/Agbele",
    "Tonabu/Opopo",
  ],
  KOSEOFE: [
    "Agboyi",
    "Agidi/Orishigun",
    "Agiliti/Maidan",
    "Araromi/Ifako",
    "Arowosegbe/Alapere",
    "Bamgbe/Elebiju",
    "Idera",
    "Ikosi Isheri",
    "Ikosi Oke",
    "Isheri Olowora",
    "Mende",
    "Odo-Ogun/Ajegunle",
    "Odogbolu",
    "Ogudu",
    "Ojota",
    "Olubori/Mosafejo",
    "Orile Oworo",
    "Orile Ikosi",
    "Orile Ketu",
    "Shangisha/Magodo",
  ],
  "LAGOS ISLAND": [
    "Ajele",
    "Alagba/Obadina",
    "Anikantamo",
    "Araromi Odo",
    "Balogun",
    "Epetedo East",
    "Epetedo West",
    "Idumoyingbo",
    "Udunganran/Idumagbo",
    "Ikoyi",
    "Ilupeju/Ebute Awo",
    "Isale Gangan",
    "Lafiaji",
    "Odam",
    "Ore-Arin/Idumota",
    "Okepopo East",
    "Okepopo West",
    "Oke-Awo/Agarawu",
    "Olosun/Ojo Ota",
    "Oluwole",
    "Victoria Island",
  ],
  "LAGOS MAINLAND": [
    "Abule Ijesha",
    "Abule Oja",
    "Adekunle/Aiyetoro",
    "Aderupoko/Ijebu Quarters",
    "Alagomeji",
    "Aloba/Desalu",
    "Araromi",
    "Botanical Garden",
    "Freeman/Glover",
    "Harvey",
    "Iponri/Olaleye",
    "Makoko",
    "Ojo-Oniyun",
    "Okobaba",
    "Onike/Oyadiran",
    "Otto",
    "Oyingbo",
    "Salami/Baiyewunmi",
  ],
  MUSHIN: [
    "Alafia/Adeoyo",
    "Alakara",
    "Babalosa",
    "Idi-Araba",
    "Idi-Oro/Idi-Olowo",
    "Igbehin",
    "Ilupeju",
    "Ilupeju Industrial",
    "Kayode/Fadeyi",
    "Moshalashi/Agoro",
    "Mushin/Atewolara",
    "Odo Eran/Ogunlana",
    "Oduselu/Ola",
    "Ojuwoye",
    "Olateju",
    "Onitire",
    "Owodunni",
    "Papa Ajao",
  ],
  OJO: [
    "Ajangbadi",
    "Egan",
    "Etegbin",
    "Iba",
    "Igbo-Elerin",
    "Ijanikin",
    "Ilogbo-Elegba",
    "Ira",
    "Irewe",
    "Kemberi",
    "Ojo Town",
    "Okokomaiko",
    "Oto-Awori",
    "Sabo-Oniba",
    "Taffi",
  ],
  "OSHODI ISOLO": [
    "Afariogun",
    "Aigbaka",
    "Ailegun",
    "Ajao Estate",
    "Akingbaye",
    "Alagbeji",
    "Apena",
    "Bolade",
    "Ewutuntun",
    "Fadu",
    "Ifoshin",
    "Igbehinadun",
    "Ilamoshe",
    "Ilasamaja",
    "Ishaga/Ire Akari",
    "Isolo",
    "Mafoluku",
    "Ogunnoloko",
    "Oke Afa",
    "Okota",
    "Ejigbo",
    "Isolo",
    "Jakande",
    "Oluyeye",
    "Shogunle",
  ],
  SHOMOLU: [
    "Aiyetoro/Mafowoku",
    "Akoka/Anu-Oluwapo",
    "Apelehin",
    "Bajulaiye",
    "Bashua East & West",
    "Ibuowo/Owotutu",
    "Igbari",
    "Igbobi/Fadeyi",
    "Ijebu Tedo",
    "Ilaje",
    "Bariga",
    "Onipan",
    "Palmgroove",
    "Okesuna/Alase",
    "Orile Somolu/Alade",
    "Owode/Orile Bariga",
    "Pedro",
    "Gbagada",
    "Seriki-Okuta",
  ],
  SURULERE: [
    "Adeniran Ogunsanya",
    "Ogunbiade",
    "Airways",
    "Akinhanmi Cole",
    "Araile",
    "Arolu",
    "Babatunde Ayilara",
    "Bale",
    "Baruwa",
    "Bayaoje",
    "Coker",
    "Gbambari",
    "Gbaja Obele-Odan",
    "Ilafue",
    "Eric Moore",
    "Yaba",
    "Iregba",
    "Iresaadu",
    "Irone",
    "Jinadu Aiyetoro",
    "Maayi",
    "Mosafejo Ojuelegba",
    "Ojuelegba",
    "Barracks",
    "Stadium",
    "Obele Oniwala",
    "Odo-Olowu",
    "Ogunsami/Karounmi",
    "Osho",
    "Ramoni",
    "Sanusi",
    "Savage",
    "Shitta Nak Olemoh",
  ],
};
